# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20160906_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Critic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('url', models.CharField(max_length=250)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Person')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Organization')),
            ],
        ),
    ]
