# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_critic'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='critic',
            field=models.ManyToManyField(to='movies.Critic'),
        ),
    ]
