# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_critic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='critic',
        ),
        migrations.AddField(
            model_name='critic',
            name='movie',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
            preserve_default=False,
        ),
    ]
