# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20160907_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critic',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critics', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='genre', to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Organization'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
